version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    reviewers: [MeltanoLabs/engineering]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers: [MeltanoLabs/engineering]
